version: "3.9"
services:
  db:
    container_name: "db"
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "8485:5432"
  
  app:
    container_name: "app"
    restart: always
    build: .
    networks:
      - mynetwork
    ports:
      - "3000:5555"
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "npm run typeorm migration:run -- -d src/shared/typeorm/connection && npm run dev"
    depends_on:
      - db

    
networks:
  mynetwork: