version: '3.7'
services:
    db:
        image: 'postgres:latest'
        environment:
                POSTGRES_PASSWORD: admin
                POSTGRES_USER: postgres
                POSTGRES_DB: postgres
        volumes:
        - ./pgdata:/var/lib/postgresql/data
        ports:
        - "3000:3000"